### PR TITLE
Added two books for reference

### PR DESCRIPTION
**Pull request by prahaladbelavadi**

### CODE REVIEW

**Comment by LearningNerd** [comment]
Thanks @prahaladbelavadi :) I am indeed recommending those books, they're both excellent! I'll be using this repo to share materials for a class I'm teaching that starts this week. The curriculum is still pretty experimental and always changing, but I decided to finally go ahead and make it public even if it isn't done yet.

I won't be taking pull requests just yet though, since I haven't had a chance to get any of the content in here yet. But always open to suggestions. :)

**Comment by prahaladbelavadi** [comment]
Fair enough
I'm glad you're taking on this initiative to teach people JS, 
If there's anything I can help with, Do let me know
I've been curating a bunch of forks of repositories that serve as guides at [belavadi](github.com/belavadi) that I figured would be helpful on Web, cryptorgaphy and bitcoin.
Do check em out to see if any can be used as references.
Good Luck :)

**Comment by prahaladbelavadi** [comment]
What are your thoughts on creating a [github pages](https://pages.github.com/) site for this content such that people inexperienced with Github can access it too ?

**Comment by LearningNerd** [comment]
@prahaladbelavadi awesome, I'll check out that repo! And about GitHub pages site -- yes, that was my original goal but it does take a bit more work to set that all up and make it look nice. :) This is only the alpha version really so I figured it would make sense to build it up and iterative, improving it in stages. It's a lot of work as it is, even without thinking about formatting or design, hehe.

**Pull request closed without merging**
